// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package hms.bedsidemonitor;

public final class PatientImpl_Stub
    extends java.rmi.server.RemoteStub
    implements hms.common.Patient
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getPatientFirstName_0;
    private static java.lang.reflect.Method $method_getPatientLastName_1;
    private static java.lang.reflect.Method $method_getPatientMiddleName_2;
    private static java.lang.reflect.Method $method_setPatientFirstName_3;
    private static java.lang.reflect.Method $method_setPatientLastName_4;
    private static java.lang.reflect.Method $method_setPatientMiddleName_5;
    
    static {
	try {
	    $method_getPatientFirstName_0 = hms.common.Patient.class.getMethod("getPatientFirstName", new java.lang.Class[] {});
	    $method_getPatientLastName_1 = hms.common.Patient.class.getMethod("getPatientLastName", new java.lang.Class[] {});
	    $method_getPatientMiddleName_2 = hms.common.Patient.class.getMethod("getPatientMiddleName", new java.lang.Class[] {});
	    $method_setPatientFirstName_3 = hms.common.Patient.class.getMethod("setPatientFirstName", new java.lang.Class[] {java.lang.String.class});
	    $method_setPatientLastName_4 = hms.common.Patient.class.getMethod("setPatientLastName", new java.lang.Class[] {java.lang.String.class});
	    $method_setPatientMiddleName_5 = hms.common.Patient.class.getMethod("setPatientMiddleName", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public PatientImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getPatientFirstName()
    public java.lang.String getPatientFirstName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPatientFirstName_0, null, 5538068990030116291L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPatientLastName()
    public java.lang.String getPatientLastName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPatientLastName_1, null, -7513726246346256499L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getPatientMiddleName()
    public java.lang.String getPatientMiddleName()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getPatientMiddleName_2, null, 1581958062568966215L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setPatientFirstName(String)
    public void setPatientFirstName(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setPatientFirstName_3, new java.lang.Object[] {$param_String_1}, -2848685150261989859L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setPatientLastName(String)
    public void setPatientLastName(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setPatientLastName_4, new java.lang.Object[] {$param_String_1}, 3984513882735841595L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setPatientMiddleName(String)
    public void setPatientMiddleName(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setPatientMiddleName_5, new java.lang.Object[] {$param_String_1}, -8606732436619393633L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
